apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plan-db-admin-secret
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: plan-db-admin
    creationPolicy: Owner
    template:
      mergePolicy: Merge
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password }}"
        username: "admin"
        uri: "postgresql://admin:{{ .password }}@plan-db-rw.plan.svc.cluster.local:5432/plan"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pg-password-generator
