apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plan-db-user-secret
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: plan-db-user
    creationPolicy: Owner
    template:
      mergePolicy: Merge
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password }}"
        username: "user"
        jdbc-uri: "jdbc:postgresql://plan-db-rw.plan.svc.cluster.local:5432/plan?password={{ .password }}&user=user"
        uri: "postgresql://user:{{ .password }}@plan-db-rw.plan.svc.cluster.local:5432/plan"
        pgpass: "plan-db-rw.plan.svc.cluster.local:5432:plan:user:{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pg-password-generator
