# Development environment using Kubernetes directly
# Since DevPod requires Docker for devcontainers, we'll use kubectl directly

# To start development environment:
# 1. Deploy database and Hasura to Kubernetes
# 2. Run frontend locally with hot reload
# 3. Use port forwarding for database access

# Commands:
# kubectl apply -f environments/kubernetes/overlays/dev/
# cd frontend && bun run dev
# kubectl port-forward svc/plan-dev-postgres 5432:5432
# kubectl port-forward svc/plan-dev-hasura 8080:8080