kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: plan-dev
nodes:
  - role: control-plane
    extraPortMappings:
      # PostgreSQL
      - containerPort: 30432
        hostPort: 5432
        protocol: TCP
      # Frontend
      - containerPort: 30000
        hostPort: 3000
        protocol: TCP
