apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-http-route.yaml
  - db/atlas-schema.yaml
