apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: ci
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-workflow
  dependencies:
    - name: push
      eventSourceName: github
      eventName: with-api-credentials
      filters:
        data:
          - path: headers.X-Github-Event
            type: string
            value: ["push"]
          - path: body.repository.full_name
            type: string
            value: ["simonbrundin/plan"]
    - name: frontend
      eventSourceName: github
      eventName: with-api-credentials
      filters:
        dataLogicalOperator: "or"
        data:
          - path: '[body.commits.#.modified.#(%"*frontend*")#,body.commits.#.added.#(%"*frontend*")#,body.commits.#.removed.#(%"*frontend*")#]'
            type: string
            value:
              - "(\\bfrontend/*)"

  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ci-
                namespace: argo-events
              spec:
                entrypoint: entrypoint
                volumes:
                  - name: source-repo
                    persistentVolumeClaim:
                      claimName: plan-repo
                  - name: deployment-pipeline
                    persistentVolumeClaim:
                      claimName: deployment-pipeline
                arguments:
                  parameters:
                    - name: source-folder
                      value: "frontend"
                    - name: tag
                      # TODO: hur löser jag att uppdatera tag och semver?
                      value: "{{workflow.creationTimestamp.YYYYMMDD-HHmm}}"
                    - name: repo-name
                      value: "plan"
                    - name: source-repo-url
                      value: "github.com/simonbrundin/plan.git"
                    - name: registry-address
                      value: "ghcr.io/simonbrundin"
                    - name: registry-username
                      value: "simonbrundin"
                    - name: registry-password-env
                      value: GITHUB_TOKEN
                templates:
                  - name: entrypoint
                    dag:
                      tasks:
                        - name: ci
                          templateRef:
                            name: deployment-pipeline
                            template: ci
                            clusterScope: true
