apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: commit
spec:
  template:
    serviceAccountName: argo-workflow
  dependencies:
    - name: github
      eventSourceName: github
      # Detta måste matcha nyckeln du har i EventSource (i ditt exempel: "with-api-credentials")
      eventName: with-api-credentials
      filters:
        data:
          # matcha full repository name "owner/name"
          - path: headers.X-Github-Event
            type: string
            value:
              - push
          - path: body.repository.full_name
            type: string
            value:
              - simonbrundin/plan
          # matcha branch (refs/heads/<branch>)
          # - path: body.baseref
          #   type: string
          #   value:
          #     - refs/heads/main
          # Tsdfsdest
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: commit-stage-
                namespace: argo-events
              spec:
                entrypoint: entrypoint
                arguments:
                  parameters:
                    - name: repo-url
                      value: "github.com/simonbrundin/plan.git"
                    - name: git-commit
                      value: "commit-sha-eller-tag"
                    - name: github-token
                      value: "ditt-github-token"
                    - name: repo-owner
                      value: "simonbrundin"
                    - name: repo-name
                      value: "plan"
                    # testssd
                volumeClaimTemplates: # define volume, same syntax as k8s Pod spec
                  - metadata:
                      name: repo # name of volume claim
                    spec:
                      accessModes: ["ReadWriteMany"]
                      resources:
                        requests:
                          storage: 1Gi
                templates:
                  - name: entrypoint
                    steps: # You should only reference external "templates" in a "steps" or "dag" "template".
                      - - name: start
                          templateRef:
                            name: commit-stage-template
                            template: all-steps
                            clusterScope: true
                          # arguments:
                          #   parameters:
                          #     - name: repo-name
                          #       value: "{{workflow.parameters.repo-name}}"
                          #     - name: repo-url
                          #       value: "{{workflow.parameters.repo-url}}"
                          #     - name: github-token
                          #       value: "{{workflow.parameters.github-token}}"
                          #     - name: git-commit
                          #       value: "{{workflow.parameters.git-commit}}"
                        # sdcssdftestsddfskdssddfsdsdffsdfs
# sdsaaaaaaaaaaaaaaaaa
