apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: commit
spec:
  template:
    serviceAccountName: argo-workflow
  dependencies:
    - name: github
      eventSourceName: github
      # Detta måste matcha nyckeln du har i EventSource (i ditt exempel: "with-api-credentials")
      eventName: with-api-credentials
      filters:
        data:
          # matcha full repository name "owner/name"
          - path: headers.X-Github-Event
            type: string
            value:
              - push
          - path: body.repository.full_name
            type: string
            value:
              - simonbrundin/plan
          # matcha branch (refs/heads/<branch>)
          # - path: body.baseref
          #   type: string
          #   value:
          #     - refs/heads/main
          # Tsdfsdest
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: commit-stage-
                namespace: plan
              spec:
                entrypoint: commit-stage
                templates:
                  - name: commit-stage
                    templareRef:
                      name: all-steps
                      template: commit-stage-template
