apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-api
spec:
  template:
    spec:
      containers:
        - name: api
          # sha-a2d1eac
          image: ghcr.io/simonbrundin/plan-api:sha-a2d1eac
          env:
            - name: AUTH_DISABLED
              value: "false"
