apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-api
spec:
  template:
    spec:
      containers:
        - name: api
          # sha-4ab1edb
          image: ghcr.io/simonbrundin/plan-api:sha-7ec3ff2
          env:
            - name: AUTH_DISABLED
              value: "false"
