apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-api
spec:
  template:
    spec:
      containers:
        - name: api
          # sha-4ab1edb
          image: ghcr.io/simonbrundin/plan-api:sha-38afc94
          env:
            - name: AUTH_DISABLED
              value: "false"
            - name: NUXT_SESSION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: NUXT_SESSION_PASSWORD
            # Keep SESSION_SECRET for backwards compatibility during rollout
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: NUXT_SESSION_PASSWORD
