apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-app
spec:
  template:
    spec:
      containers:
        - name: plan-app
          # Updated by .github/workflows/commit.nuxt.yaml.
          image: ghcr.io/simonbrundin/plan@sha256:237d47df53422fda6a82e85ff829f50b98050409308b4e719145cd9f83430dce
          env:
            - name: NODE_ENV
              value: "production"
            - name: NUXT_PUBLIC_APP_URL
              value: "https://plan.simonbrundin.com"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: plan-db-user
                  key: uri
            - name: NUXT_SESSION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: NUXT_SESSION_PASSWORD
            - name: NUXT_OAUTH_ZITADEL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: NUXT_OAUTH_ZITADEL_CLIENT_ID
            - name: NUXT_OAUTH_ZITADEL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: NUXT_OAUTH_ZITADEL_CLIENT_SECRET
            - name: NUXT_OAUTH_ZITADEL_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: NUXT_OAUTH_ZITADEL_DOMAIN
            - name: NUXT_OAUTH_ZITADEL_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: NUXT_OAUTH_ZITADEL_REDIRECT_URL
