apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-app
spec:
  template:
    spec:
      containers:
        - name: plan-app
          image: ghcr.io/simonbrundin/plan@sha256:0aaf4c1bbee00b4d3c14fe700d520831db6f73f5afe48081d3f1612a6ef421b3
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: plan-db-user
                  key: uri
            - name: NUXT_SESSION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: NUXT_SESSION_PASSWORD
            - name: NUXT_OAUTH_ZITADEL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: NUXT_OAUTH_ZITADEL_CLIENT_ID
            - name: NUXT_OAUTH_ZITADEL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: NUXT_OAUTH_ZITADEL_CLIENT_SECRET
            - name: NUXT_OAUTH_ZITADEL_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: NUXT_OAUTH_ZITADEL_DOMAIN
            - name: NUXT_OAUTH_ZITADEL_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: NUXT_OAUTH_ZITADEL_REDIRECT_URL
