apiVersion: v1
kind: Secret
metadata:
  name: auth
  namespace: plan
type: Opaque
stringData:
  NUXT_SESSION_PASSWORD: 5c3ddb48cdb04a05aed90cdb9330cbc2
  NUXT_OAUTH_ZITADEL_CLIENT_ID: "391431970426454645"
  NUXT_OAUTH_ZITADEL_CLIENT_SECRET: ""
  NUXT_OAUTH_ZITADEL_DOMAIN: auth.simonbrundin.com
  NUXT_OAUTH_ZITADEL_REDIRECT_URL: https://plan.simonbrundin.com/api/auth/zitadel
