apiVersion: v1
kind: Secret
metadata:
  name: plan-db-user
  namespace: plan
  labels:
    cnpg.io/reload: "true"
type: Opaque
stringData:
  password: plan
  username: plan
  uri: postgresql://plan:plan@postgres:5432/plan
  jdbc-uri: postgresql://plan:plan@postgres:5432/plan
  pgpass: postgres://plan:plan@postgres:5432/plan
