apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
  - HTTP-route.yaml
  - service.yaml
  - db
  - hasura
  - kargo
  - secrets
images:
  - name: ghcr.io/simonbrundin/plan
    newTag: "frontend-1.6.4"
