apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hasura
spec:
  interval: 5m
  chart:
    spec:
      chart: hasura
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: hasura-extra
        namespace: plan
  install:
    createNamespace: true
    replace: true
  upgrade:
    remediation:
      retries: 3
    force: true
  values:
    dbUrl:
      valueFrom:
        secretKeyRef:
          name: hasura-env
          key: HASURA_GRAPHQL_DATABASE_URL
    adminSecret:
      valueFrom:
        secretKeyRef:
          name: hasura-env
          key: HASURA_GRAPHQL_ADMIN_SECRET
    secret:
      jwtSecret:
        type: "RS256"
        jwk_url: "https://auth.simonbrundin.com/application/o/plan/.well-known/jwks.json"
        claims_map:
          x-hasura-default-role: "user"
          x-hasura-allowed-roles:
            - "user"
            - "admin"
          x-hasura-user-sub: "sub"
    config:
      enableConsole: true
      corsDomains: "*"
    # Disable secret creation - we use dbUrl and adminSecret above
    secretName: ""
