apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: plan-pipeline
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend-warehouse
      sources:
        availabilityStrategy: All
        direct: true
  verification:
    analysisTemplates:
      - name: acceptance-stage

  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/simonbrundin/plan.git
            checkout:
              - branch: main
                path: ./src
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./src/environments/kubernetes/overlays/test
            images:
              - image: ghcr.io/simonbrundin/plan
        - uses: git-commit
          as: commit
          config:
            path: ./src
            message: "Update test image to ${{ imageFrom('ghcr.io/simonbrundin/plan').Tag }}"
        - uses: git-push
          config:
            path: ./src

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: plan-pipeline
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend-warehouse
      sources:
        stages:
          - test

  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/simonbrundin/plan.git
            checkout:
              - branch: main
                path: ./src
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./src/environments/kubernetes/overlays/prod
            images:
              - image: ghcr.io/simonbrundin/plan
        - uses: git-commit
          as: commit
          config:
            path: ./src
            message: "Update prod image to ${{ imageFrom('ghcr.io/simonbrundin/plan').Tag }}"
        - uses: git-push
          config:
            path: ./src
