apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: plan-pipeline
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend-warehouse
      sources:
        availabilityStrategy: All
        direct: true
  verification:
    analysisTemplates:
      - name: acceptance-stage

  promotionTemplate:
    spec:
      steps:
        - uses: promote
          config:
            stage: test

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: plan-pipeline
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend-warehouse
      sources:
        stages:
          - test

  promotionTemplate:
    spec:
      steps:
        - uses: promote
          config:
            stage: prod
