services:
  postgres:
    image: postgres:16-alpine
    container_name: plan-dev-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: plan
      POSTGRES_PASSWORD: plan
      POSTGRES_DB: plan
    volumes:
      - ../kubernetes/overlays/prod/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ../kubernetes/overlays/dev/db/seed-data.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
      - plan-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plan"]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  plan-postgres-data:
