apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth
  namespace: plan
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: auth
  dataFrom:
    - extract:
        key: prod/plan/auth
