apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: atlasschema-plan
spec:
  urlFrom:
    secretKeyRef:
      key: uri
      name: plan-db-app
  schema:
    sql: |
      create table users (
        id int
          constraint users_pk
            primary key,
        name varchar(40) not null,
        email varchar(40) not null,
        created_at timestamp with time zone default CURRENT_TIMESTAMP not null
      );
