apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plan-db-secret
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: plan-db-app
    creationPolicy: Merge
    template:
      mergePolicy: Merge
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password }}"
        pgpass: "plan-db-rw:5432:app:app:{{ .password }}"
        jdbc-uri: "jdbc:postgresql://plan-db-rw.default:5432/app?password={{ .password }}&user=app"
        uri: "postgresql://app:{{ .password }}@plan-db-rw.default:5432/app"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pg-password-generator
