apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - HTTP-route.yaml
  - github-secret.yaml
  - service.yaml
  - db
patches:
  - path: patches/deployment.yaml
images:
  - name: ghcr.io/simonbrundin/plan
    newTag: "0.0.3"
