apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - HTTP-route.yaml
  - service.yaml
  - db.yaml
  - db-secret.yaml
  - push-secret.yaml
  - db-schema.yaml
  - password-generator.yaml
  - workflow-hello-world.yaml
  - workflow-sa.yaml
  - workflow-rolebinding.yaml
  # - workflows/commit.yaml
  # - workflows/eventbus.yaml

namespace: plan

images:
  - name: simonbrundin/plan
    newTag: "0.0.11"

patches:
  - path: patch.yaml
