-- Schema for Plan app

CREATE TABLE "users" (
  "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "sub" VARCHAR(255) NOT NULL UNIQUE,
  "email" VARCHAR(40) NOT NULL UNIQUE,
  "first_name" VARCHAR(16),
  "last_name" VARCHAR(40),
  "created" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY("id")
);

CREATE TABLE "statuses" (
  "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(32) NOT NULL UNIQUE,
  "label" VARCHAR(64) NOT NULL,
  "created" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY("id")
);

CREATE TABLE "goals" (
  "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "title" VARCHAR(64),
  "icon" VARCHAR(100) DEFAULT 'heroicons:star',
  "status_id" INTEGER DEFAULT 1 NOT NULL,
  "created" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "started" TIMESTAMPTZ,
  "finished" TIMESTAMPTZ,
  "inbox" INTEGER DEFAULT 1 NOT NULL,
  PRIMARY KEY("id"),
  FOREIGN KEY("status_id") REFERENCES "statuses"("id")
);

CREATE TABLE "user_goals" (
  "user_id" INTEGER NOT NULL,
  "goal_id" INTEGER NOT NULL,
  PRIMARY KEY("user_id", "goal_id")
);

CREATE TABLE "goal_relations" (
  "parent_id" INTEGER NOT NULL,
  "child_id" INTEGER NOT NULL,
  "order" INTEGER NOT NULL DEFAULT 0,
  "weight" INTEGER NOT NULL DEFAULT 10,
  PRIMARY KEY("parent_id", "child_id")
);

ALTER TABLE "user_goals"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "user_goals"
ADD FOREIGN KEY("goal_id") REFERENCES "goals"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "goal_relations"
ADD FOREIGN KEY("parent_id") REFERENCES "goals"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "goal_relations"
ADD FOREIGN KEY("child_id") REFERENCES "goals"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

-- Dependencies: X must be completed before Y can start
CREATE TABLE "goal_dependencies" (
  "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "goal_id" INTEGER NOT NULL,           -- the goal that depends on another
  "depends_on_id" INTEGER NOT NULL,    -- the goal that must be completed first
  "created" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY("goal_id", "depends_on_id"),
  CONSTRAINT no_self_reference CHECK (goal_id != depends_on_id)
);

ALTER TABLE "goal_dependencies"
ADD FOREIGN KEY("goal_id") REFERENCES "goals"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "goal_dependencies"
ADD FOREIGN KEY("depends_on_id") REFERENCES "goals"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

-- Status updates: history of status changes for goals
CREATE TABLE "status_updates" (
  "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "goal_id" INTEGER NOT NULL,
  "from_status_id" INTEGER REFERENCES "statuses"("id"),
  "to_status_id" INTEGER NOT NULL REFERENCES "statuses"("id"),
  "changed_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY("id")
);

ALTER TABLE "status_updates"
ADD FOREIGN KEY("goal_id") REFERENCES "goals"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

-- Seed: Statuses
INSERT INTO statuses (name, label) VALUES
  ('define', 'Defining'),
  ('plan', 'Planning'),
  ('execute', 'Executing'),
  ('verify', 'Verifying'),
  ('completed', 'Completed')
ON CONFLICT DO NOTHING;

-- Seed: Root goal
INSERT INTO goals (id, title, icon) VALUES (1, 'Root', 'heroicons:home') ON CONFLICT DO NOTHING;
