apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - HTTP-route.yaml
  - db
  - hasura
  - secrets
  - plan-authentik-blueprint.yaml

patches:
  - path: deployment-patch.yaml

images:
  - name: ghcr.io/simonbrundin/plan
    newTag: "frontend-202606121357"
