apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: plan-db-schema
  namespace: plan
spec:
  url: "postgresql://admin@plan-db-rw.plan.svc.cluster.local:5432/plan?search_path=public"
  schema:
    configMapKeyRef:
      key: schema.sql
      name: plan-db-schema
  schemas:
    - "public"
