apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: plan-db-schema
  namespace: plan
spec:
  urlFrom:
    secretKeyRef:
      name: plan-db-admin
      key: uri
  dir:
    path: /schema
  devURLFrom:
    secretKeyRef:
      name: plan-db-admin
      key: uri