apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: plan-db-schema
    files:
      - schema.sql=schema.sql

resources:
  - db.yaml
  - grant-job.yaml
  - atlas-schema.yaml
