apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml

configMapGenerator:
  - name: postgres-config
    data:
      POSTGRES_PORT: "5432"
      POSTGRES_DATABASE_URL: "postgres://plan:plan@postgres:5432/plan"
    options:
      disableNameSuffixHash: true
  - name: postgres-init-scripts
    files:
      - 01-schema.sql=schema.sql
      - 02-seed-data.sql=seed-data.sql
    options:
      disableNameSuffixHash: true
