apiVersion: v1
kind: Secret
metadata:
  name: auth
  namespace: plan
type: Opaque
stringData:
  NUXT_SESSION_PASSWORD: ENC[AES256_GCM,data:P9+Zih4VIvxjl12cagIhHPgj2tCnbPlUEXI+eNzS/z4HhekP29ByMhjAWQ==,iv:hT5bW/oRGr+/92KwFLbOBpqpWOFdkAK5Vj92g+Ca1uA=,tag:iMRl5alCrED3J98x/tPnbA==,type:str]
  NUXT_OAUTH_AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:9KmbG35jZjCy3xe7V00JxZB31qeGjmN0c2tUzOCA1Q/dao1mhwthdw==,iv://btqdo6uchjv9uioZJvYJ/7f+0+0ILRtwuvIdIR6cE=,tag:y3DuzIkFyvdt3kv6BVa4xw==,type:str]
  NUXT_OAUTH_AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:WnpitO4uhVcE3l8t+SP3Lkn6xrFJiKacZ3jp90+D5/I=,iv:wTR7Val5Vi3cBnkyBEKr+iROXR1JabgCjZBmSNeGgdM=,tag:+pVJKx3aDm3/Z5SHxMH1SQ==,type:str]
  NUXT_OAUTH_AUTHENTIK_DOMAIN: ENC[AES256_GCM,data:TwDSu1R6vOsDRMHuv9RfYOhN0WS4,iv:IQSXyrj9utsXbTEHl5Bo3+dWKqTjdjEMl2NAw1zeVwc=,tag:P4oApE9Q/NpvJOQsEHxhng==,type:str]
  NUXT_OAUTH_AUTHENTIK_REDIRECT_URL: ENC[AES256_GCM,data:9B13NtfVBoXQTB4KGHscNj+XGnrSYKscW5GXYn61lrZwA3DaPbBZeL2CVe3n9eXRl2L3WaT4mrjd,iv:HaNGBbQJX3vxxU0EP31ANdeytYIPNT/V9WFfXNyw7O0=,tag:a2ZFUFBbxK89ruroXFeW3g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYjNLVVJLUHV4OXFDV1A1
        N1RMSnRGNkFhZjljdCtNenVwVzVSUWc0bDFjCnhMTnZDcWo5Um9VczJZTEVZZFhv
        Ri9RdGNUWWdLMmtQSGxSU2wrVUFiSk0KLS0tIFFmaHd0aVFXZEkvREx4OFRreHoy
        aXltUW1ZRW84TUFUaHhwek1rU1YyU3MKNOcpw98tU4/j39P8vLNk+ZfVO8FceKMm
        1mYx9MiTSzOfp0OhBRh1fHBNfl6t5tOuY2KsVE2RTjiw33D5VxqOPA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T09:00:39Z"
  mac: ENC[AES256_GCM,data:Uowml+IpJgGWCgoGvhXjPhjACqGlk+IwuzpfgAv6LtsZsPScBG/Ns22ZyZScjHR35H5mcXqc2dJ/J2P17K4xyqZUgzluQRPAoHNDJJaBmFiovdVKcYTfTN+C1zzFrN/N8s0dzrpFXJidDUTLKYG2DD5jSxZFR+4vrQ55rVVYywY=,iv:hPaenTE0lYVbMPOh3A9uhdejVDen8jttqmgkj0tEeI4=,tag:rsLgWbiDwWzG4Fg2pemW+A==,type:str]
  version: 3.13.1
