apiVersion: v1
kind: Secret
metadata:
    name: auth
    namespace: plan
type: Opaque
stringData:
    NUXT_SESSION_PASSWORD: ENC[AES256_GCM,data:wVwF97MFrFRiSaPgA4EFIwGqdmtJsUWE5RQ3gFc1dB/sAY1u4cyLXJ/iww==,iv:tkOLSnQsBRcDSiJL5XMQ+k4rN25jvlkQg4zJrea2tuw=,tag:3an/kG5WIqLXh8HttBZILg==,type:str]
    NUXT_OAUTH_ZITADEL_CLIENT_ID: ENC[AES256_GCM,data:+6ty/SCShuazfZEhZ6bM2yBz,iv:DN4Ahw8j+tiRwIek3hPMGPyPeCIW3a8L8DGqWMapSDI=,tag:AeKv2fMW/JRetkhfd5Mccg==,type:str]
    NUXT_OAUTH_ZITADEL_CLIENT_SECRET: ""
    NUXT_OAUTH_ZITADEL_DOMAIN: ENC[AES256_GCM,data:xNYfNedJ4/AeOSPEj8vDobUUFrZ5,iv:kYab/+t49KmHN02kxcHYb1oI5MxV4/2ykdGSM1mNVyY=,tag:oXgXSehrpFkdmbVqk5NmAg==,type:str]
    NUXT_OAUTH_ZITADEL_REDIRECT_URL: ENC[AES256_GCM,data:PSnNc6SsEXi50NpBXfz/9FqStz4EolA3lr1/iJ/QnQd/8C+OxiAuqDHToAqPTg==,iv:Zc/OT8pW+XqR9bxYL5SSBnd6lI58yhxEhuyWEEOtBzI=,tag:faFM6dxbedmtTGi/G9TP+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTVBBbEMvSHNpbG1tWEVZ
            ZXErYmY4TE44c1NmbXhFakJsN2ErTFNKTEhNCkx1cDBCMGJQTjBMSUpDVEZqMG9n
            cVJKL3JLSjIrRi9IRjZUdDI1Tkt6U00KLS0tIDR2NEw1UjBZbnViWGZ0MGJPOWZY
            UGhDc281dlliNVoycDVCVnBTUWR0YXcKhYWHLwdi6FY/iVsTsnJ6MeFxUjux84a2
            jy7rUx0f8OIrLlnYY9w0PwdMxjZcWq/vhwihpBS+gI9MBDe9lh9buQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T11:37:10Z"
    mac: ENC[AES256_GCM,data:GihZuK/ovHSnH8la+iu3z1Cm4LQHl1d7vqvnddoi2KmMJzEtYIl+1ZSxP4kWepPllOVzY63Lz8mK5HJPr2JNw66iZTXzsc+RLVz++UiSAFNUfPnIAj8STvaD4wUDrM8sIHyiXWkBdysQYKhKNATmQdqZ23xI2Tb0dT2Fywn/HK0=,iv:Q3VnJn6YiiHifzzN3rfv0Q4Xcq1qdJfyfKyU0efpQEk=,tag:4UQLIstcw7oO/XS6uvGkfw==,type:str]
    version: 3.13.1
