apiVersion: v1
kind: Secret
metadata:
  name: auth
  namespace: plan
type: Opaque
stringData:
  NUXT_SESSION_PASSWORD: ENC[AES256_GCM,data:gyjsb0oUWISMwpC8ewyL8FIRpjHC7xy0ZOZ+YEXTlBfw/NufVGO7kPrN0A==,iv:cODIxuv5nLji79wz8ijwxok0euClsK1553adJqVcfQk=,tag:eNjiyxbyFuOcJD8XmXcXYQ==,type:str]
  NUXT_OAUTH_AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:FYpmsRnD+/InVV5Y2JKVcbGXXm4nNch+aGucVlf6EuDe71Tlgoir+A==,iv:1eJ+fmZNG3ad8jyu6oZoDGBzItZxWQM/UjRfwsGGNLs=,tag:7rRn2+FQy3Ujv9GbPLlpfw==,type:str]
  NUXT_OAUTH_AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:HV4qnO5CeyGkpxP+ewqlsSbXgqxl2kgf8zKa9pmF1IU=,iv:HNs73BPrvxy0AviaDORcGMvc5YJztwYhB9zLX/59ifg=,tag:+6vgIeA44WFHxG07wb01/w==,type:str]
  NUXT_OAUTH_AUTHENTIK_DOMAIN: ENC[AES256_GCM,data:c5gyuq4J2qebJdJe9VE5JN8nd2FL,iv:l9rysB8xzgSjbpL/rtWTvMulRskehGGtmh7WDJdQIyY=,tag:a5DhuKVapfItoW5MoBZcyQ==,type:str]
  NUXT_OAUTH_AUTHENTIK_REDIRECT_URL: ENC[AES256_GCM,data:u08COPYLDk0KglUEITPzsPMh/pPwTdvtJmFN9IWe2MyJjBU0l9rKlDCqjNfWIRfN,iv:05DEhcj3Tqi8OnZWYC/5pgR+lXJPePy+SzkjDt0/YOs=,tag:aV8zNV2BjJWelkQQdN2J9A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObXEvUDBqTGIxeW9SOXA0
        MHFPL25id1hHM21CSnorQU1OeEp0VHVYSDFFCmJLZGZjdkxnRGRoemZWMFdIM1pT
        SDlYTVZkRUJSS0VmSmptc214TGcxMTAKLS0tIGdxNTkxRTVrNUhkcHJEZldRdGZW
        eTIyNmg1MFUrZDJHbUQ0L3NMN0JZbDQKWeg1B34xsWZ4t368DAiqD92ICdBIqGJI
        puUpXOrj4lEIFbcLW/9mA+1Y38ISY4+FWzjFmD1ezFcZrFL5peKJuw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T23:51:28Z"
  mac: ENC[AES256_GCM,data:CaXaiZMhpvYOaBCC00dTyKiTXT/YW0T9rHczvRNRNqMRD2WNh6lA6QKt3LkuFeW5C6j1AMHz5tECc0gaUv+oPhFcU0oxTSMmKAy6TlZOER1QLvA8ngXxIRh8XCba9BrjtLqxwe9/t6Ixe6LXk/GQ7w4CjBCiEK//Rr0xVSE5u20=,iv:6T7VtiNpk65pXQLOD1Ko8joIMl9jf2Ikca56AeeZT1Q=,tag:8xECL6ZDplQM6ItfiyNg0g==,type:str]
  version: 3.13.1
