apiVersion: v1
kind: Secret
metadata:
  name: hasura-env
  namespace: plan
type: Opaque
stringData:
  HASURA_GRAPHQL_DATABASE_URL: ENC[AES256_GCM,data:2RVVK1XZMhY2hqiTDbaqT9f3RzsLOFRb0KYARgYGNe+uB8cZPqdb4mFVYYyoL/aVXm7CGz4uNJxN5MTupiwC9Tr+Gy3c+qY8IvpCCJBV9gm7V95frUQsHnAdkuLdmA==,iv:MM0EtyDo0g7pARSlZ70AJC1indl7bEJnYBxNzFTvxi4=,tag:bsOPzXsjlbXyGeh50qJCAg==,type:str]
  HASURA_GRAPHQL_ADMIN_SECRET: ENC[AES256_GCM,data:OaOG8zIEkJU9fnwjIr8sws4ojF422oiRpRBBCjM=,iv:wC7j6d2XGgSyeyZzR5ctZqbneqjNJihFvu2gtGfZ15k=,tag:ilMHSmLICHHTE+2DAFOzhg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaVpEL2ozc2ZkVDRhM3Nj
        YnByNURVZmtVY3kxSlRJWlMvUytiNk9yQVZBCldwVGVJYjdxT3FvUTdRZnZxcWpk
        Rmgxc2x0K0FWU3dqYWJIOUJwZVFUNU0KLS0tIHRueW9qanlyZG1jbzdPdFpzQWc0
        dW1LUW50cnF0UUs5MUdKd0pFbmQzRnMKTfVsQT34XX0U0pG5ZepBCBHIc1EOmT1T
        Ym32Zzk4Zw9LqAmmX06VsJ+jns9at2Joxnb+jfRZ3o9/wHTlKmEGXg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:59:07Z"
  mac: ENC[AES256_GCM,data:TrQ3blGFx+DYOa9Ij8fXGiyM4HhAKiwbY1d1mtJSy2a25Rou1ySmtGdUYZPYCYcZYBX4/yDsWGn+U5IkfM2dgqNXbQP0Goji6ufhaPRIAO2vFdLFckAJWZ91ThCX/IYpbb/Yw1aZMip2QhLJywYzJ7QhhJ6hIgPP1xwK9rsLZAQ=,iv:LTfKzFGbvV+3PV0O95DuQuEkSvBqoSthZ7n5Fm4qwvc=,tag:cnZSRGbmmUj3O8HJ/6zrHQ==,type:str]
  version: 3.13.1
