apiVersion: v1
kind: Secret
metadata:
    name: plan-db-user
    namespace: plan
    labels:
        cnpg.io/reload: "true"
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:NWP7o5f8BSg7AXV7icoQ6+p4ClU/Ytw8yHqLG6ap+9o=,iv:LuMaU4IoTq6mVk5iH0Y7K8MlH7vmW41FfgG7OX2HeSw=,tag:6tqbGCgIufLZ8CxXvv9NBQ==,type:str]
    username: ENC[AES256_GCM,data:T5RFsQ==,iv:4h96Me0WWYihImBZly/KGsCApOTa50dQfUSJvH8lokA=,tag:Sjrx1p8lFZOgGxUV/4syhA==,type:str]
    jdbc-uri: ENC[AES256_GCM,data:JVNn47PEbxrkDIa4byWI8cM8mxzxOXSIpo7sV5ZL/SGlMfZ8gQJqbclbaOBk3fjzX+DtIpe2KfGH8OCZC9H3vZqhXQYDRBschdnuoxpv4kmloRkCq2UjWlZUMd022+WFjUvCGelUQt44PmBmkPBg9mA=,iv:9M67ls+nCE3VeHYnEYx34o/uSMJgmgJAqnt2RUhJ6e4=,tag:igMCPcDShFeiP6KCvFlZQA==,type:str]
    uri: ENC[AES256_GCM,data:92zLImes3IyXX3nCz0a9BiHrHBynDNsbwAlQORs3sgrDPz+8tr4Nmek4YUV+qElQdYVQ/+Np7FH1SWBINmt1048pm5kjDhahDd0Fkd5eB6QgDygq7Bv9Zvvl75n43Q==,iv:6i0c2/yyMbcjpphyEhOqASO6yY+Kfb4VzOW0VBUcfa0=,tag:ebhQJZqmF8KzzApqJ/kDaQ==,type:str]
    pgpass: ENC[AES256_GCM,data:7Bq8vCqK+Njbli6fnl3fOCg6Zzv28XuGZblcjkPAkxepZtjwPGhwkEq7mEhisTaphJ5N+bNKkm1r6Qa6wUwJmORwkEfh+KJKP5yl17KcdU63,iv:61uoQRZOOjqBnLSNzHf+yNf+lEan8ooIkowWcRM9+Js=,tag:YnLZ8WOk9fj/zzxTWDEKCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZUZYd2FTclFvbEpUWCtR
            UTFTcWMvQ1FwOFF1V2ZMa0Nvb2dYbUxJcEc0ClJDZUx1dUJlejJreEsrUVZJSmU4
            QWVEWFQrZEFGOWZBa2k1dXBvSkN4M0EKLS0tIFRhc1NjbWo0T1NTdUd4cU15M0kv
            ZmxKN05SNFZSRUlxU01VbVhlK0lSd1UKLzMIgJbVU+BUzsw4yAVx4Ug3gjxbUCWo
            h9SWpvGj8g8jlxOPyuWil8cKs+skYv6KDQzc+L87OrgyqRkY6Xer4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T09:00:39Z"
    mac: ENC[AES256_GCM,data:r2tPUiv5XQ36E3ZonyNW+QbttQo2TJwjFmyMuxnBCrgppZiJ2EBDevyoD18marsgfYLUpJyIqNh1p8cbjkIsv4W6rJ6Rgtn3hBdvehuJ3x5OiyxZ63vZgcVM4J+qqGAM8duybFudt/Bwy38BAluPp4Lxi2LnYNr5ugYBegUqa9c=,iv:c+RhngckbsPpMI1dsTDwuCx6cBvS4fo112bLed6m0mE=,tag:7Axt+mXAvo65/V+MV/XXcw==,type:str]
    version: 3.13.1
