apiVersion: v1
kind: Secret
metadata:
    name: plan-db-admin
    namespace: plan
    labels:
        cnpg.io/reload: "true"
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:+XtBk/gH9+xdrBuW7TkGE5/MoXaMZIYgiXaiD7HfCFE=,iv:3D3+r6jKEK8XvUv/iWTgTEtPe8j08iB45BD5yNQh2Hk=,tag:59YnhT27N4id7LlEJpYAQA==,type:str]
    username: ENC[AES256_GCM,data:SxToqiM=,iv:89SuG9w1+W6xolC5MSqkRL8aVaPxVCOh9VnILLkKe9I=,tag:L/mLAl71iiGTn/Lwghu+eg==,type:str]
    uri: ENC[AES256_GCM,data:lo5BYblgPFe1MgR/TRhkFGNMWggh8prjlOLEeaj8OY2ddOIdFoggGCaZHcnBfKUkrx/m2Jbl2fz/oow3AWf4DG7m0NSRLPbeM13uR9qVdNcVFildj734a80A0S+RTIRlD4r4Mjht256BwfpDjRQOHX0M,iv:iKc1tWwsox1Lp+WEKtCr0KRnlaNH6tjobrVMD35LZzY=,tag:4buRzApcKh0sqdbYnWxcVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbWQ3dkk5dFBncUVjdDNP
            dnhiajJvaXFQb2Z2QkxXZjJoL1hzVVkxWUY0ClBOdFY2TDNmc1V6c0luZW9uajcr
            Zk8yOTlrdGxVTGdhSFFRaC8ySHJtczgKLS0tIDZYbjNTYU5Ma01peCtWeEVjTE5y
            MXpkUjBCVFdKaUJqYXgwUGp6bXl1V1kKaMoBLkrbc4Q1aU4OpgttLPcXEbUTS7rc
            hvC/IGYr1yzm9+Cu9SBiWqdAJBFV8sGb7ne9NOKnedpKYXgu6qIPyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T15:47:55Z"
    mac: ENC[AES256_GCM,data:I/bz/Y/Y9vLx5V9hKjzrohCTgBnpRyi59dk/Fz3CC8fj5Q9CL1G5tep1WFo4B5/FM3CdGxugYqw/ixs+ob8yRpjl96QWCqoVa8Uza65Xq09znxjwIoccX+1Yo4GVzr+LMmIw16ecRe2JWQ4i63iPuKQXMUWuSiNEcfQZB1Hng3E=,iv:PuDWIYJkALzuOXG3WQXdCX88oYEH816YiD0kr1EZQQQ=,tag:4nBa9QNWy6n8PDt0uvlUXg==,type:str]
    version: 3.13.1
