apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: plan
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:fUKhq1Av4SmqEkQBqr9L+Pg/4EJFWApaVbpWf+VDLTW2tKM7YKiJvAfQraCRlqdEEyBOC2JOJXhJjJVKtw8xoNWmgIIhHiZIgoBf1GPHJpYtcZo7CQIh+bzRBaT/fczllyVvBwJcAvZO+aIUUGr/7WAg6ChUmEnc87jwJqgF0dgA8l1hBpXiaKYGO1/7kVY=,iv:GWDFUK04agoo+c7rXcLprAiSIXi0+1Dnv6V1eHXZpPA=,tag:y4uqqlNzhyCdF2OSaLu67A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQU1QraklPRk8wREl5WXRZ
            c1F0bHpGRmJXd04zOVZyeDV3QTBKdGNUUmtBCnA4ZnFncTIzbnd2QlhGVjdmcWpK
            cnN6MGZrZ29VWmtheDlFbTB3VXRmVU0KLS0tIHo2cUhPcFVwdzJXOHN0MC9keStM
            b29DS1h6RXZsZVJibExoeXJyUVluUk0KAt2m3AaZlAuqIfGY2GGW52KKGnOVEGvA
            GpxmNOC+4S5A5jGJvxkCTA/U0F6hTFgWnj8lw1vpLdwy3Z7HmHwsSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T12:30:43Z"
    mac: ENC[AES256_GCM,data:ychXe+mpNheCh2SeBJIWH6Hvr3PEYs/Vqz2xyiJJrF6JFr8wUkhNvoWI5Ez2jSDnRahducp2+2vxwljMZGOaKTL9vLdK1OuoCOzv1UTJ+k5mZFSygBDh4ZKRMExUZ/VxsOVzDXRbPdxqQDJFMLMxJPT4782Bd4QXz1qvvOn7qNw=,iv:PSLocSBG9jKvYMJgGSy9rypfaDE/8/A4BNTN6NLwTzY=,tag:nOZWete3UtLHCas3jHOR9A==,type:str]
    version: 3.13.1
