apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: plan
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:TWKvjVOKPbbuM/SEGOHTHYnr9IWX+Ma0CPCb243MUd0OuKpzTq5f2ZZB4xA4ete86lEklyCoWZNS/hBedo0zpR9CCGPSFfDC61EEE7VIk6cpxdw3VPEzljF+7kbl2OXNkYhIInoEkTPJIUmtlLjsG8j2hBYtbW7caeYVdT/zuQYfWu8V0+2FZAxvGVG5isA=,iv:hHzr2fK8m9RFrrbaK7U7+Wu9HRhqZYb9weD6I++ZH3g=,tag:YW1of/moL5KB0aE1Q9z3iA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYmtXR1EzL29WMVMwWGpr
            VzkwZkNmQzZlMlV2ZytWMjJIOHVSWGtteFFFCndDZGh6QU5qNnhGNXlzRE4rOW9z
            Qy81S1JVUFVrcUNrVG5PbzYva082NjQKLS0tIExpQUpoZ09nY25QamRTTjA1TFdG
            b1lRMEtOeG0wRWtzUVA5QWFibzV0WVkKDsJceCXrpBN36T6mjv2k8KMcui+YJ8Hb
            R4u1FoXDgnetog61IcbDP2IULh5F3IPT+gBxUIUP9LZr6crLXnJF+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T09:00:39Z"
    mac: ENC[AES256_GCM,data:0BvPA0kDIe5fbmMtc8XbZsc1aG+62PrRs+SCd3yBhnluKkIiJ62W1OyviVs9342jakH+oLcuqpK2Lsbqv4VrR2KkfmaDo9LCVhYRDO6OAeY+YeLEDAGKnxrHoYPZAl1vg8FWy4bcv64UhS9wwc+6E9PvjqjwbpLGU0eJDuYWFkE=,iv:hsVf/AU52J397PJ9DgjrSQpFST+U9Cb9jXNLt+QlIfc=,tag:Rgr4748l8K6SLPgQrYsvaQ==,type:str]
    version: 3.13.1
