apiVersion: v1
kind: Secret
metadata:
    name: hasura
    namespace: plan
type: Opaque
stringData:
    HASURA_GRAPHQL_ADMIN_SECRET: ENC[AES256_GCM,data:jmsSvYjUXcX2/DMGD151QRZUpo1K4OgJsb6QGz4=,iv:SAE8T6sZ6JDv8Sjf39KddQRE4q6FJ7uP6EHyNwTq0Og=,tag:I/qwv68ufel37ZcnZda/nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaFhidEZ5OXhPTjhYWUtJ
            ZjQ2cWlJSTcvZkh0RVhJQksrWEROZXhUMEFVCldLeUN3UC85Wk9VNktDUEpJUExt
            djVZVExxRTFpcEJpNytOd3ZJTlUyUVUKLS0tIEhTN0V2aHJYcmVvMThrTkY4NThk
            aEdOR3lVb3BJSkJVaUxpYk1RcGMyY1kK2FS2cptK3itRm86Lo7b9SgY1rKjv5Ipv
            XLh3v7ikoqEKCQ38aWKiYj5JHINVpGclZq0fZzkb98zDjETAhIib9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T12:51:04Z"
    mac: ENC[AES256_GCM,data:BW91cDYV2s3LuyfqkUAXWChk6LENGcWAmL5rdxDcATolkP4JnN/SzouuFsrDTyDH92dqWDzIg8H0XcmXvDx2LmGzjTiMNDjg2eia8NYSEUDWKBbveT0SfPzse1RJ1kilcBQ/S61TAvexjzjrrMgbM9hZUt7gqf9suHKO/OkG6RM=,iv:G9LSyLDzNtsoOw0WL9BJx1IzoB9L2CR1hi0dGbo1ltI=,tag:w/sFpM4/b+zkn6nFo6mxxg==,type:str]
    version: 3.13.1
