apiVersion: v1
kind: Secret
metadata:
    name: plan-db-admin
    namespace: plan
    labels:
        cnpg.io/reload: "true"
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:wqyB9/Nq0DkP2BRuq5r7PRc0soPDHkIxDYg+unRb+As=,iv:aHi3UA6JuhcjLm09emDL/jmymPtTNi/MNWXdi1oTDXo=,tag:MZCeHCCK80PnPmV/OEZQhQ==,type:str]
    username: ENC[AES256_GCM,data:WEnwFqE=,iv:j3UggcrNZKr+VJ6JUbVoiE2yzw9m1xvlbvS5DQoLW40=,tag:pCww/jbqMgXA42Fwo9SFcw==,type:str]
    uri: ENC[AES256_GCM,data:bV8udHObpfN74keg3znrBEiQlIAf3UdFqwrm/9SEtUAkuurY1LihHWQDBABdzuvlFjBlYQjl9WCsRtd0uXJh31liqw5v13Msiiid3MLTkks7wRxY6Aq9ns3RrQYocIY=,iv:bzrMRsXuVK0YiipC5LvqFqLKnsT8EwYpiUI345yQMAY=,tag:bJlJdQGxrEoBp4jsXIMv1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTXdyVlZVSm9hcUZua0ow
            am41L1JqOVpBOVY4eXNZWFIwSjN1OUxuL0RFCnlwTVEycHNnRnRjeGViL1dBWGFq
            QkZYNVptVG9INUJ6ZHY4ckRvSTZwU28KLS0tIFJKcCtmTGRhTXNGbGRqUWpYRUsx
            b0pGWTgwcXhHdEFZY0JRRXJSNXRQNVUKkc9ZrfI9Zo+7Fnz+tbgvlABxiPZilz1L
            AvN1ibIrgIgoIWMLfrC8igCfZUhjBQ2k7oN0RA2rJxIX/W/kcB3OzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T09:00:39Z"
    mac: ENC[AES256_GCM,data:/81zCBeOEfSffKimJ6kr8VkqNcV2nwFH6zDJXilUId67NoH6VRQq9glhgK42xX4/THlgRDXnh+GR7dhAmqgH00mqPoPekE3xUQ9hLtN/yBdkOUbfmJ3RVZZLCaJFuiNbLl8tddzJekphxJRbjuNLpKKTjIMdDxAdhnzzBo7lQZA=,iv:v+sHNjO66YwnwQcfGusCY1ZqDNIdqjEjcG2npPpu/u4=,tag:GVh9b6YdE5eFgJl+lT1Nxg==,type:str]
    version: 3.13.1
