// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Simon",
            "url": "https://github.com/simonreming"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/goals": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get all goals for the authenticated user",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["goals"],
                "summary": "List all goals",
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/Goal"}}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Create a new goal for the authenticated user",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["goals"],
                "summary": "Create a new goal",
                "parameters": [{
                    "description": "Goal data",
                    "name": "goal",
                    "in": "body",
                    "required": true,
                    "schema": {"$ref": "#/definitions/CreateGoalRequest"}
                }],
                "responses": {
                    "201": {"description": "Created", "schema": {"$ref": "#/definitions/Goal"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/api/goals/prioritized": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get all active goals sorted by priority",
                "produces": ["application/json"],
                "tags": ["goals"],
                "summary": "Get prioritized goals",
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/PrioritizedGoal"}}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/api/goals/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get a single goal with all its relations and dependencies",
                "produces": ["application/json"],
                "tags": ["goals"],
                "summary": "Get a goal by ID",
                "parameters": [{
                    "type": "integer",
                    "description": "Goal ID",
                    "name": "id",
                    "in": "path",
                    "required": true
                }],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/GetGoalResponse"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "patch": {
                "security": [{"BearerAuth": []}],
                "description": "Update a goal's title, icon, started, or finished status",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["goals"],
                "summary": "Update a goal",
                "parameters": [
                    {"type": "integer", "description": "Goal ID", "name": "id", "in": "path", "required": true},
                    {"description": "Update data", "name": "goal", "in": "body", "required": true, "schema": {"$ref": "#/definitions/UpdateGoalRequest"}}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/Goal"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Delete a goal and all its relations",
                "produces": ["application/json"],
                "tags": ["goals"],
                "summary": "Delete a goal",
                "parameters": [{"type": "integer", "description": "Goal ID", "name": "id", "in": "path", "required": true}],
                "responses": {
                    "200": {"description": "OK"},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/api/goals/relations": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Create a relation between two goals",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["relations"],
                "summary": "Create a parent-child relation",
                "parameters": [{"description": "Relation data", "name": "relation", "in": "body", "required": true, "schema": {"$ref": "#/definitions/CreateRelationRequest"}}],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/ChildRelation"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "patch": {
                "security": [{"BearerAuth": []}],
                "description": "Update a relation's order and weight",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["relations"],
                "summary": "Update a relation",
                "parameters": [{"description": "Update data", "name": "relation", "in": "body", "required": true, "schema": {"$ref": "#/definitions/UpdateRelationRequest"}}],
                "responses": {
                    "200": {"description": "OK"},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Delete a parent-child relation",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["relations"],
                "summary": "Delete a relation",
                "parameters": [{"description": "Relation data", "name": "relation", "in": "body", "required": true, "schema": {"$ref": "#/definitions/DeleteRelationRequest"}}],
                "responses": {
                    "200": {"description": "OK"},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/api/goals/dependencies": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Create a dependency between two goals",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["dependencies"],
                "summary": "Create a dependency",
                "parameters": [{"description": "Dependency data", "name": "dependency", "in": "body", "required": true, "schema": {"$ref": "#/definitions/CreateDependencyRequest"}}],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/GoalDependency"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Delete a dependency between two goals",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["dependencies"],
                "summary": "Delete a dependency",
                "parameters": [{"description": "Dependency data", "name": "dependency", "in": "body", "required": true, "schema": {"$ref": "#/definitions/DeleteDependencyRequest"}}],
                "responses": {
                    "200": {"description": "OK"},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "401": {"description": "Unauthorized", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "403": {"description": "Forbidden", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API is running",
                "produces": ["application/json"],
                "tags": ["health"],
                "summary": "Health check",
                "responses": {
                    "200": {"description": "OK"}
                }
            }
        }
    },
    "definitions": {
        "Goal": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "title": {"type": "string"},
                "icon": {"type": "string"},
                "created": {"type": "string"},
                "started": {"type": "string"},
                "finished": {"type": "string"},
                "inbox": {"type": "integer"}
            }
        },
        "ChildRelation": {
            "type": "object",
            "properties": {
                "child_id": {"type": "integer"},
                "order": {"type": "integer"},
                "weight": {"type": "integer"}
            }
        },
        "GoalDependency": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "goal_id": {"type": "integer"},
                "depends_on_id": {"type": "integer"},
                "created": {"type": "string"}
            }
        },
        "PrioritizedGoal": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "title": {"type": "string"},
                "icon": {"type": "string"},
                "created": {"type": "string"},
                "started": {"type": "string"},
                "finished": {"type": "string"},
                "inbox": {"type": "integer"},
                "weight": {"type": "integer"},
                "parentTitle": {"type": "string"},
                "parentId": {"type": "integer"}
            }
        },
        "GetGoalResponse": {
            "type": "object",
            "properties": {
                "goal": {"$ref": "#/definitions/GoalWithRelations"},
                "children": {"type": "array", "items": {}},
                "parents": {"type": "array", "items": {}},
                "allGoals": {"type": "array", "items": {"$ref": "#/definitions/Goal"}},
                "dependencies": {"type": "array", "items": {"$ref": "#/definitions/GoalDependency"}},
                "dependsOn": {"type": "array", "items": {"$ref": "#/definitions/Goal"}},
                "blocking": {"type": "array", "items": {"$ref": "#/definitions/Goal"}}
            }
        },
        "GoalWithRelations": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "title": {"type": "string"},
                "icon": {"type": "string"},
                "created": {"type": "string"},
                "started": {"type": "string"},
                "finished": {"type": "string"},
                "inbox": {"type": "integer"},
                "childRelations": {"type": "array", "items": {"$ref": "#/definitions/ChildRelation"}},
                "parentRelations": {"type": "array", "items": {}}
            }
        },
        "CreateGoalRequest": {
            "type": "object",
            "required": ["title"],
            "properties": {
                "title": {"type": "string"},
                "icon": {"type": "string"}
            }
        },
        "UpdateGoalRequest": {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "icon": {"type": "string"},
                "started": {"type": "string"},
                "finished": {"type": "string"}
            }
        },
        "CreateRelationRequest": {
            "type": "object",
            "required": ["childId", "parentId"],
            "properties": {
                "childId": {"type": "integer"},
                "parentId": {"type": "integer"},
                "order": {"type": "integer"},
                "weight": {"type": "integer"}
            }
        },
        "UpdateRelationRequest": {
            "type": "object",
            "required": ["childId", "parentId"],
            "properties": {
                "childId": {"type": "integer"},
                "parentId": {"type": "integer"},
                "order": {"type": "integer"},
                "weight": {"type": "integer"}
            }
        },
        "DeleteRelationRequest": {
            "type": "object",
            "required": ["childId", "parentId"],
            "properties": {
                "childId": {"type": "integer"},
                "parentId": {"type": "integer"}
            }
        },
        "CreateDependencyRequest": {
            "type": "object",
            "required": ["goalId", "dependsOnId"],
            "properties": {
                "goalId": {"type": "integer"},
                "dependsOnId": {"type": "integer"}
            }
        },
        "DeleteDependencyRequest": {
            "type": "object",
            "required": ["goalId", "dependsOnId"],
            "properties": {
                "goalId": {"type": "integer"},
                "dependsOnId": {"type": "integer"}
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {"type": "string"}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Type \"Bearer\" followed by a token. For development, use \"user_<id>\" format (e.g., \"user_1\")"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Goals Management API",
	Description:      "API for managing goals with parent-child relations and dependencies",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
