apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: plan-pipeline
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend-warehouse
      sources:
        availabilityStrategy: All
        direct: true
  verification:
    analysisTemplates:
      - name: acceptance-stage

  promotionTemplate:
    spec:
    destination:
      git:
        repoURL: https://github.com/simonbrundin/plan.git
        repoBranch: main

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: plan-pipeline
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend-warehouse
      sources:
        stages:
          - test

  promotionTemplate:
    spec:
