apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: plan-pipeline
spec:
  subscriptions:
    warehouse: frontend-warehouse
  freightConstraints:
    - sources:
        - kind: GitRepository
          name: frontend-warehouse
        - kind: Image
          name: frontend-warehouse
  promotionTemplate:
    spec:
      approvals:
        auto: true
      steps:
        - uses: cli.exec
          with:
            image: loftsh/vcluster:0.15.0
            command: >
              vcluster create test --namespace test-vcluster --update-current=false --connect=false
        - uses: cli.exec
          with:
            image: ghcr.io/argoproj/argocd:latest
            command: >
              kubectl --context=vcluster_test_test-vcluster apply -k deployment/overlays/template-ephemeral
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: plan-pipeline
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend-warehouse
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: plan-pipeline
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend-warehouse
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: plan-pipeline
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend-warehouse
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: openpr
              value: "true"
