kind: Stage
apiVersion: kargo.akuity.io/v1alpha1
metadata:
  name: production-frontend
  namespace: plan-pipeline
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend-warehouse
      sources:
        direct: true
        stages: []
