apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-cred
  namespace: plan-pipeline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend # <-- din ESO SecretStore/ClusterSecretStore
    kind: ClusterSecretStore # eller ClusterSecretStore
  target:
    name: ghcr-cred # namnet p책 K8s-secreten som skapas
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "simonbrundin",
                "password": "{{ .token }}",
                "auth": "{{ printf "%s:%s" "<GITHUB_USERNAME>" .token | b64enc }}"
              }
            }
          }
  data:
    - secretKey: token # f채ltet i SecretStore d채r din PAT finns
      remoteRef:
        key: github-pat # namnet i backend (t.ex. AWS SM, Vault)
        property: token # f채ltet i den hemligheten (din PAT)
