name: Acceptance Phase
on:
  workflow_call:
    inputs:
      image:
        required: false
        default: ""
        type: string
jobs:
  acceptance:
    uses: simonbrundin/deployment-pipeline/.github/workflows/acceptance.yaml@main
    secrets:
      DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
    with:
      source-dir: frontend
      image-digest: ${{ inputs.image-digest }}
