name: CI - Backend
run-name: CI - Backend
on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
jobs:
  ci-backend:
    runs-on: ubuntu-latest
    services:
      dagger-engine:
        image: registry.dagger.io/engine:v0.18.17
        options: --privileged
        volumes:
          - /run/dagger:/run/dagger
          - /var/lib/dagger:/var/lib/dagger
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          path: source-repo

      - name: Checkout deployment pipeline
        uses: actions/checkout@v3
        with:
          repository: simonbrundin/deployment-pipeline
          token: ${{ secrets.GITHUB_TOKEN }}
          path: deployment-pipeline
          ref: main

      - name: Download Dagger CLI
        run: |
          curl -L https://github.com/dagger/dagger/releases/download/v0.18.17/dagger_v0.18.17_linux_amd64.tar.gz | tar -xz -C /usr/local/bin
          chmod +x /usr/local/bin/dagger

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install devDependencies
        run: npm install --legacy-peer-deps
        working-directory: source-repo/frontend

      - run: npx semantic-release
        working-directory: source-repo/frontend
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Run Dagger CI
        run: |
          cd deployment-pipeline/dagger-modules/pipeline
          dagger call ci \
            --image-name ${{ github.event.repository.name }} \
            --registry-address ghcr.io/simonbrundin \
            --source-dir $GITHUB_WORKSPACE/source-repo/backend\
            --tag ${{ env.RELEASE_VERSION }} \
            --username simonbrundin \
            --secret ${{ secrets.REGISTRY_PASSWORD }} \
            --multiArch
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

      # - name: Commit changes
      #   run: |
      #     cd source-repo
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git add .
      #     git commit -m "Release ${{ env.TAG }} [skip ci]" || exit 0
      #
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
      #     directory: source-repo
