name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Hämta repository
        uses: actions/checkout@v4
        with:
          path: app

      - name: Hämta Deployment Pipeline
        uses: actions/checkout@v4
        with:
          repository: simonbrundin/deployment-pipeline
          path: pipeline

      - name: Kör CI
        uses: dagger/dagger-for-github@v8.3.0
        with:
          verb: call
          module: ./pipeline/dagger-modules/pipeline
          args:
            ci --source-dir app --registry-address ${{ vars.REGISTRY_ADDRESS }}
            --image-name ${{ github.event.repository.name }} --tag ${{
            github.run_number }} --username ${{ vars.REGISTRY_USERNAME }}
            --secret ${{ secrets.REGISTRY_PASSWORD }}
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
