name: CI för Nuxt applikation
on: [push]

permissions:
  contents: read
  packages: write
jobs:
  tests:
    uses: simonbrundin/deployment-pipeline/.github/workflows/run-tests-bun.yaml@main
    with:
      package-json-path: frontend
  ci:
    needs: tests
    uses: simonbrundin/deployment-pipeline/.github/workflows/ci.yaml@main
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
    with:
      dockerfile: frontend/Dockerfile
      dockerfile-context: frontend
