name: CI
on: [push]

permissions:
  contents: read
  packages: write
jobs:
  commit:
    uses: simonbrundin/deployment-pipeline/.github/workflows/ci.yaml@main
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
    with:
      dockerfile: frontend/Dockerfile
      dockerfile-context: frontend
