name: CI för Nuxt applikation
on:
  push:
    paths:
      - src/nuxt/**
jobs:
  unit-tests:
    permissions:
      contents: read
    uses: >-
      simonbrundin/deployment-pipeline/.github/workflows/run-tests-bun.yaml@main
    with:
      package-json-path: src/nuxt
  build-publish-image:
    needs: unit-tests
    permissions:
      contents: read
      packages: write
    uses: >-
      simonbrundin/deployment-pipeline/.github/workflows/commit.build-publish-image.yaml@main
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
    with:
      dockerfile: src/nuxt/Dockerfile
      dockerfile-context: src/nuxt
      registry: ghcr.io/simonbrundin/plan
  store-image-tag:
    needs: build-publish-image
    runs-on: ubuntu-latest
    steps:
      - name: Store image tag
        run: |
          echo "${{ needs.build-publish-image.outputs.image }}" > image-tag.txt
      - name: Upload image tag
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: image-tag.txt
          retention-days: 1
