name: Commit Phase

on: [push, workflow_dispatch]

jobs:
  commit:
    uses: simonbrundin/deployment-pipeline/.github/workflows/commit-phase.yaml@main
    with:
      source-dir: frontend
    secrets:
      DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
