apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: plan-app
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "800m"
          env:
            - name: NODE_ENV
              value: "production"
